// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Retrieves the appropriate [FirebaseOptions] for the current platform.
  ///
  /// - If running on the web, returns the web-specific options.
  /// - For Android, iOS, and macOS, it returns the corresponding options.
  /// - Throws [UnsupportedError] if the platform is Linux or unsupported.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration for web applications.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxQPdGbSiD5dcVGh88R23lGMImKCxtKs',
    appId: '1:426509858399:web:4b4738cef4e35016264dea',
    messagingSenderId: '426509858399',
    projectId: 'spotify0101',
    authDomain: 'spotify0101.firebaseapp.com',
    storageBucket: 'spotify0101.appspot.com',
  );

  /// Firebase configuration for Android applications.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwAF_v-n8bHO0Nrf_x0VvqALRxIN436OM',
    appId: '1:426509858399:android:a9f0dd91f4d88cb2264dea',
    messagingSenderId: '426509858399',
    projectId: 'spotify0101',
    storageBucket: 'spotify0101.appspot.com',
  );

  /// Firebase configuration for iOS applications.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBumD8nn8O9ISMsaxhBT-duBGi1YSZAsSk',
    appId: '1:426509858399:ios:78d9d14dc192a583264dea',
    messagingSenderId: '426509858399',
    projectId: 'spotify0101',
    storageBucket: 'spotify0101.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  /// Firebase configuration for macOS applications.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBumD8nn8O9ISMsaxhBT-duBGi1YSZAsSk',
    appId: '1:426509858399:ios:78d9d14dc192a583264dea',
    messagingSenderId: '426509858399',
    projectId: 'spotify0101',
    storageBucket: 'spotify0101.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  // Firebase configuration for Windows applications.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwxQPdGbSiD5dcVGh88R23lGMImKCxtKs',
    appId: '1:426509858399:web:7367e344006c4003264dea',
    messagingSenderId: '426509858399',
    projectId: 'spotify0101',
    authDomain: 'spotify0101.firebaseapp.com',
    storageBucket: 'spotify0101.appspot.com',
  );
}
